export PS1="\u@\h:\w\$ "
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export TERM=linux

# Enable bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
elif [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
fi
